"""initial schema

Revision ID: f25afbb94bc7
Revises: 
Create Date: 2026-07-13 11:59:38.017485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25afbb94bc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_cache_id'), ['id'], unique=False)

    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_config_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_config_key'), ['key'], unique=True)

    op.create_table('confidence_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_compliance', sa.Float(), nullable=False),
    sa.Column('historical', sa.Float(), nullable=False),
    sa.Column('cross_hospital', sa.Float(), nullable=False),
    sa.Column('trend', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confidence_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confidence_weights_id'), ['id'], unique=False)

    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_name'), ['name'], unique=True)

    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('default_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_indicators_id'), ['id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('expression_type', sa.String(length=50), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rules_id'), ['id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    op.create_table('anomaly_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('rate_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('benchmark', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_results_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_results_month'), ['month'], unique=False)
        batch_op.create_index('ix_ar_hosp_month', ['hospital_id', 'month'], unique=False)
        batch_op.create_index('ix_ar_outlier', ['is_outlier'], unique=False)

    op.create_table('clinical_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('analysis_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_insights', schema=None) as batch_op:
        batch_op.create_index('ix_ci_hosp_month', ['hospital_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_insights_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_insights_month'), ['month'], unique=False)

    op.create_table('confidence_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('indicator_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('indicators_data', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confidence_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confidence_scores_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confidence_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confidence_scores_month'), ['month'], unique=False)
        batch_op.create_index('ix_cs_hosp_month', ['hospital_id', 'month'], unique=False)
        batch_op.create_index('ix_cs_level', ['level'], unique=False)

    op.create_table('hospital_indicator_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('weight_override', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'indicator_id', name='uq_hospital_indicator')
    )
    with op.batch_alter_table('hospital_indicator_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_indicator_config_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_indicator_config_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_indicator_config_indicator_id'), ['indicator_id'], unique=False)

    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicator_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicator_values_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_values_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_values_indicator_id'), ['indicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_values_month'), ['month'], unique=False)
        batch_op.create_index('ix_iv_hosp_month_ind', ['hospital_id', 'month', 'indicator_id'], unique=False)
        batch_op.create_index('ix_iv_month', ['month'], unique=False)

    op.create_table('quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rule_compliance', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('outlier_penalty', sa.Float(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.create_index('ix_qs_hosp_month', ['hospital_id', 'month'], unique=False)
        batch_op.create_index('ix_qs_month', ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_scores_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_scores_month'), ['month'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_month'), ['month'], unique=False)
        batch_op.create_index('ix_vr_hosp_month', ['hospital_id', 'month'], unique=False)
        batch_op.create_index('ix_vr_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_vr_status')
        batch_op.drop_index('ix_vr_hosp_month')
        batch_op.drop_index(batch_op.f('ix_validation_results_month'))
        batch_op.drop_index(batch_op.f('ix_validation_results_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_hospital_id'))

    op.drop_table('validation_results')
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_scores_month'))
        batch_op.drop_index(batch_op.f('ix_quality_scores_id'))
        batch_op.drop_index(batch_op.f('ix_quality_scores_hospital_id'))
        batch_op.drop_index('ix_qs_month')
        batch_op.drop_index('ix_qs_hosp_month')

    op.drop_table('quality_scores')
    with op.batch_alter_table('indicator_values', schema=None) as batch_op:
        batch_op.drop_index('ix_iv_month')
        batch_op.drop_index('ix_iv_hosp_month_ind')
        batch_op.drop_index(batch_op.f('ix_indicator_values_month'))
        batch_op.drop_index(batch_op.f('ix_indicator_values_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_indicator_values_id'))
        batch_op.drop_index(batch_op.f('ix_indicator_values_hospital_id'))

    op.drop_table('indicator_values')
    with op.batch_alter_table('hospital_indicator_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_indicator_config_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_indicator_config_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_indicator_config_hospital_id'))

    op.drop_table('hospital_indicator_config')
    with op.batch_alter_table('confidence_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_cs_level')
        batch_op.drop_index('ix_cs_hosp_month')
        batch_op.drop_index(batch_op.f('ix_confidence_scores_month'))
        batch_op.drop_index(batch_op.f('ix_confidence_scores_id'))
        batch_op.drop_index(batch_op.f('ix_confidence_scores_hospital_id'))

    op.drop_table('confidence_scores')
    with op.batch_alter_table('clinical_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_insights_month'))
        batch_op.drop_index(batch_op.f('ix_clinical_insights_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_insights_hospital_id'))
        batch_op.drop_index('ix_ci_hosp_month')

    op.drop_table('clinical_insights')
    with op.batch_alter_table('anomaly_results', schema=None) as batch_op:
        batch_op.drop_index('ix_ar_outlier')
        batch_op.drop_index('ix_ar_hosp_month')
        batch_op.drop_index(batch_op.f('ix_anomaly_results_month'))
        batch_op.drop_index(batch_op.f('ix_anomaly_results_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_results_hospital_id'))

    op.drop_table('anomaly_results')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_id'))
        batch_op.drop_index(batch_op.f('ix_rules_code'))

    op.drop_table('rules')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_id'))
        batch_op.drop_index(batch_op.f('ix_indicators_code'))

    op.drop_table('indicators')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_name'))
        batch_op.drop_index(batch_op.f('ix_hospitals_id'))

    op.drop_table('hospitals')
    with op.batch_alter_table('confidence_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confidence_weights_id'))

    op.drop_table('confidence_weights')
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_config_key'))
        batch_op.drop_index(batch_op.f('ix_app_config_id'))

    op.drop_table('app_config')
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_cache_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_cache_cache_key'))

    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
