"""Short-lived snapshots of removed indicator values, backing "Undo Remove Data".

Remove Data deletes a whole ``(hospital(s), month)`` slice of raw
``IndicatorValue`` rows. Because that is a bulk delete with no recycle bin, the
rows are copied here *before* they are deleted so the user can restore them for
a few minutes without re-uploading the file.

Only raw values are kept. Derived results (quality scores, validations,
anomalies, confidence, clinical insights) are regenerated by re-running
analysis, so there is no reason to snapshot them.

The store is process-local, bounded and best-effort:

* entries expire after :data:`TTL_SECONDS`;
* at most :data:`MAX_SNAPSHOTS` entries are kept (oldest evicted first);
* a removal with more than :data:`MAX_ROWS` rows is reported as *not
  undoable* rather than growing memory without limit.

Everything is guarded by a lock because the API runs in a thread pool.
"""
from __future__ import annotations

import threading
import time
import uuid
from collections import OrderedDict
from typing import Dict, List, Optional

TTL_SECONDS = 600          # undo window: 10 minutes
MAX_ROWS = 100_000         # rows kept per snapshot
MAX_SNAPSHOTS = 5          # simultaneous removals that stay undoable

_lock = threading.Lock()
_snapshots: "OrderedDict[str, Dict]" = OrderedDict()


def _prune_locked() -> None:
    """Drop expired entries. Caller must hold ``_lock``."""
    now = time.time()
    for token in [t for t, e in _snapshots.items() if e["expires_at"] <= now]:
        _snapshots.pop(token, None)


def create(rows: List[Dict], meta: Dict) -> Optional[Dict]:
    """Store ``rows`` (plain dicts) under a fresh token.

    Returns a descriptor the API can hand to the client, or ``None`` when the
    snapshot is too large to keep. ``meta`` is opaque to the store (the API
    stashes scope / month / hospital info in it).
    """
    if not rows or len(rows) > MAX_ROWS:
        return None
    token = uuid.uuid4().hex
    entry = {
        "token": token,
        "rows": rows,
        "meta": meta or {},
        "expires_at": time.time() + TTL_SECONDS,
    }
    with _lock:
        _prune_locked()
        _snapshots[token] = entry
        while len(_snapshots) > MAX_SNAPSHOTS:
            _snapshots.popitem(last=False)
    return {
        "token": token,
        "expires_in": TTL_SECONDS,
        "expires_at": entry["expires_at"],
        "rows": len(rows),
    }


def get(token: str) -> Optional[Dict]:
    """Return the live snapshot for ``token``, or ``None`` if missing/expired."""
    if not token:
        return None
    with _lock:
        _prune_locked()
        return _snapshots.get(token)


def drop(token: str) -> None:
    """Forget a snapshot (used once it has been restored)."""
    with _lock:
        _snapshots.pop(token, None)


def clear() -> None:
    """Wipe the store — test helper."""
    with _lock:
        _snapshots.clear()


def stats() -> Dict:
    """Introspection: how many snapshots are live and how many rows they hold."""
    with _lock:
        _prune_locked()
        return {
            "snapshots": len(_snapshots),
            "rows": sum(len(e["rows"]) for e in _snapshots.values()),
            "ttl_seconds": TTL_SECONDS,
        }
