_RULES_CONFIG = {
    "eq_tolerance": 0.01,
    "cs_rate_threshold": 80.0,
    "nvd_rate_threshold": 10.0,
    "zscore_threshold": 2.5,
    "month_over_factor": 2.0,
    "month_under_factor": 0.5,
    "maternal_over_factor": 4.0,
    "neonatal_over_factor": 4.0,
}


RULE_REF_CODES = {
    "R001": ["2", "3", "4", "5"],
    "R002": ["2", "2.a", "2.b"],
    "R003": ["2", "2.c", "2.d", "2.e", "2.f", "2.g", "2.h", "2.i", "2.j"],
    "R004": ["2", "2.k", "2.l"],
    "R005": ["2", "2.m", "2.n"],
    "R006": ["5", "5.b.1", "5.b.2"],
    "R007": ["5", "5.c", "5.d"],
    "R008": ["5.b.1", "5"],
    "R009": ["5.b.2", "5"],
    "R010": ["5.d", "5"],
    "R011": ["6", "6.a", "6.b", "6.c"],
    "R012": ["6.d", "6"],
    "R013": ["6.e", "6"],
    "R014": ["6.f", "6"],
    "R015": ["6.g", "6"],
    "R016": ["7", "7.a", "7.b"],
    "R017": ["8", "8.a", "8.b"],
    "R018": ["7", "2"],
    "R019": ["8", "2"],
    "R020": ["9", "6"],
    "R021": ["10.a.1", "10.a"],
    "R022": ["10.a.2", "10.a"],
    "R023": ["10.a.3", "10.a"],
    "R024": ["10.a.1", "10.a.1.1", "10.a.1.2"],
    "R025": ["10.a.2", "10.a.2.1", "10.a.2.2"],
    "R026": ["10.a.3", "10.a.3.1", "10.a.3.2", "10.a.3.3"],
    "R027": ["10.e.1", "10.e"],
    "R028": ["10.e.2", "10.e"],
    "R029": ["10.e.3", "10.e"],
    "R030": ["10.e", "10.e.1", "10.e.2", "10.e.3"],
    "R031": ["10.a", "10"],
    "R032": ["10.e", "10"],
    "R033": ["10.f", "10"],
    "R034": ["10.m", "10"],
    "R035": ["10.d", "10"],
    "R036": ["10.c", "10"],
    "R037": ["10.b", "10"],
    "R038": ["10.l", "10"],
    "R039": ["10.h", "10"],
    "R040": ["10.i", "10"],
    "R041": ["5", "2"],
    "R042": ["3", "2"],
    "R043": ["6.f", "6"],
    "R044": ["6.g", "6"],
    "R045": ["11", "6"],
    "R046": ["17", "6"],
    "R047": ["7", "2"],
    "R048": ["16", "6"],
    "R049": ["10", "2"],
    "R050": ["10.a", "2"],
    "R051": ["2"],
    "R052": ["2"],
    "R053": ["6"],
    "R054": ["11"],
    "R055": ["17"],
    "R056": ["2", "3", "4", "5", "6", "7", "8", "10", "11", "16", "17"],
    "R057": ["2", "3", "4", "5", "6", "7", "8", "10", "11", "16", "17"],
    "R058": ["2"],
    "R059": ["6"],
    "R060": ["2", "3", "4", "5", "6", "7", "8", "10", "11", "16", "17"],
}


RULE_CATALOG = [
    {"code": "R001", "name": "Total Deliveries >= NVD + Assisted + C-sections", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R002", "name": "Primigravida + Multigravida ≈ Total Deliveries", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R003", "name": "Age group sum ≈ Total Deliveries", "type": "LOGIC", "severity": "LOW"},
    {"code": "R004", "name": "In-facility + Out-of-facility ≈ Total Deliveries", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R005", "name": "Low Risk + High Risk ≈ Total Deliveries", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R006", "name": "Emergency + Planned C/S = Total C-sections", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R007", "name": "Primary + Repeat C/S = Total C-sections", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R008", "name": "Emergency C/S <= Total C-sections", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R009", "name": "Planned C/S <= Total C-sections", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R010", "name": "Repeat C/S <= Total C-sections", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R011", "name": "Male + Female + Unknown = Live Births", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R012", "name": "Multiple Pregnancy <= Live Births", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R013", "name": "Twins/Multiples count <= Live Births", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R014", "name": "Preterm Births <= Live Births", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R015", "name": "Low Birth Weight <= Live Births", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R016", "name": "Fresh + Macerated Stillbirth = Fetal Deaths", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R017", "name": "1st + 2nd Trimester = Abortions", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R018", "name": "Fetal Deaths <= Total Deliveries", "type": "LOGIC", "severity": "HIGH"},
    {"code": "R019", "name": "Abortions <= Total Deliveries", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R020", "name": "Congenital Anomalies <= Live Births", "type": "LOGIC", "severity": "MEDIUM"},
    {"code": "R021", "name": "Postpartum Hemorrhage <= Hemorrhage", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R022", "name": "Antepartum Hemorrhage <= Hemorrhage", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R023", "name": "Early Pregnancy Hemorrhage <= Hemorrhage", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R024", "name": "Primary + Secondary Severe <= PPH", "type": "CLINICAL", "severity": "MEDIUM"},
    {"code": "R025", "name": "Placental Abruption + Previa <= APH", "type": "CLINICAL", "severity": "MEDIUM"},
    {"code": "R026", "name": "Ectopic + Abortion Bleeding + Molar <= EPH", "type": "CLINICAL", "severity": "MEDIUM"},
    {"code": "R027", "name": "Severe Preeclampsia <= Hypertensive Disorders", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R028", "name": "HELLP Syndrome <= Hypertensive Disorders", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R029", "name": "Eclampsia <= Hypertensive Disorders", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R030", "name": "Preeclampsia + HELLP + Eclampsia <= Hypertensive Disorders", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R031", "name": "Hemorrhage <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R032", "name": "Hypertensive Disorders <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R033", "name": "Sepsis <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R034", "name": "Unplanned ICU Admission <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R035", "name": "Hysterectomy <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R036", "name": "Relaparotomy <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R037", "name": "Uterine Rupture <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R038", "name": "Anaesthesia Complications <= SMM", "type": "CLINICAL", "severity": "MEDIUM"},
    {"code": "R039", "name": "Cardiac ICU Admission <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R040", "name": "Renal Failure/Dialysis <= SMM", "type": "CLINICAL", "severity": "HIGH"},
    {"code": "R041", "name": "C-Section Rate > 80%", "type": "BENCHMARK", "severity": "HIGH"},
    {"code": "R042", "name": "NVD Rate < 10%", "type": "BENCHMARK", "severity": "HIGH"},
    {"code": "R043", "name": "Preterm Birth Rate outlier", "type": "BENCHMARK", "severity": "MEDIUM"},
    {"code": "R044", "name": "Low Birth Weight Rate outlier", "type": "BENCHMARK", "severity": "MEDIUM"},
    {"code": "R045", "name": "Maternal Mortality Ratio outlier", "type": "BENCHMARK", "severity": "HIGH"},
    {"code": "R046", "name": "Neonatal Mortality Rate outlier", "type": "BENCHMARK", "severity": "HIGH"},
    {"code": "R047", "name": "Stillbirth Rate outlier", "type": "BENCHMARK", "severity": "MEDIUM"},
    {"code": "R048", "name": "NICU Admission Rate outlier", "type": "BENCHMARK", "severity": "MEDIUM"},
    {"code": "R049", "name": "SMM Rate outlier", "type": "BENCHMARK", "severity": "HIGH"},
    {"code": "R050", "name": "Hemorrhage Rate outlier", "type": "BENCHMARK", "severity": "HIGH"},
    {"code": "R051", "name": "Deliveries > 2x previous month", "type": "DATA_QUALITY", "severity": "HIGH"},
    {"code": "R052", "name": "Deliveries < 50% of previous month", "type": "DATA_QUALITY", "severity": "HIGH"},
    {"code": "R053", "name": "Live Births > 2x previous month", "type": "DATA_QUALITY", "severity": "HIGH"},
    {"code": "R054", "name": "Maternal Deaths increased >300%", "type": "DATA_QUALITY", "severity": "CRITICAL"},
    {"code": "R055", "name": "Neonatal Deaths increased >300%", "type": "DATA_QUALITY", "severity": "CRITICAL"},
    {"code": "R056", "name": "Negative indicator value", "type": "DATA_QUALITY", "severity": "HIGH"},
    {"code": "R057", "name": "Decimal value for count indicator", "type": "DATA_QUALITY", "severity": "LOW"},
    {"code": "R058", "name": "Missing Total Deliveries", "type": "DATA_QUALITY", "severity": "HIGH"},
    {"code": "R059", "name": "Missing Live Births", "type": "DATA_QUALITY", "severity": "HIGH"},
    {"code": "R060", "name": "All indicators zero (possible non-operational facility)", "type": "DATA_QUALITY", "severity": "CRITICAL"},
]
