"""Seed the 60 validation rules into the database."""
import json
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.database import SessionLocal, init_db
from app.models import Rule


RULES = [
    # ============================================
    # GROUP 1: BASIC LOGIC (R001-R020)
    # ============================================
    {
        "code": "R001",
        "name": "Total Deliveries >= Normal Vaginal + Assisted Vaginal + Caesarean Sections",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "ge",
        "params": json.dumps({"parent": "2", "children": ["3", "4", "5"]}),
        "description": "Total Deliveries must be >= sum of NVD + Assisted + C-sections",
    },
    {
        "code": "R002",
        "name": "Primigravida + Multigravida ≈ Total Deliveries",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "2", "children": ["2.a", "2.b"]}),
        "description": "Sum of Primigravida and Multigravida should equal Total Deliveries",
    },
    {
        "code": "R003",
        "name": "Age group sum ≈ Total Deliveries",
        "rule_type": "LOGIC",
        "severity": "LOW",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "2", "children": ["2.c", "2.d", "2.e", "2.f", "2.g", "2.h", "2.i", "2.j"]}),
        "description": "Sum of all age groups should equal Total Deliveries",
    },
    {
        "code": "R004",
        "name": "In-facility + Out-of-facility ≈ Total Deliveries",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "2", "children": ["2.k", "2.l"]}),
        "description": "Sum of in-facility and out-of-facility deliveries should equal Total Deliveries",
    },
    {
        "code": "R005",
        "name": "Low Risk + High Risk ≈ Total Deliveries",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "2", "children": ["2.m", "2.n"]}),
        "description": "Sum of low risk and high risk deliveries should equal Total Deliveries",
    },
    {
        "code": "R006",
        "name": "Emergency + Planned C/S = Total C-sections",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "5", "children": ["5.b.1", "5.b.2"]}),
        "description": "Sum of Emergency and Planned C/S should equal total Caesarean Sections",
    },
    {
        "code": "R007",
        "name": "Primary + Repeat C/S = Total C-sections",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "5", "children": ["5.c", "5.d"]}),
        "description": "Sum of Primary and Repeat C/S should equal total Caesarean Sections",
    },
    {
        "code": "R008",
        "name": "Emergency C/S <= Total C-sections",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "5.b.1", "parent": "5"}),
        "description": "Emergency C/S must not exceed total Caesarean Sections",
    },
    {
        "code": "R009",
        "name": "Planned C/S <= Total C-sections",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "5.b.2", "parent": "5"}),
        "description": "Planned C/S must not exceed total Caesarean Sections",
    },
    {
        "code": "R010",
        "name": "Repeat C/S <= Total C-sections",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "5.d", "parent": "5"}),
        "description": "Repeat C/S must not exceed total Caesarean Sections",
    },
    {
        "code": "R011",
        "name": "Male + Female + Unknown = Live Births",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "6", "children": ["6.a", "6.b", "6.c"]}),
        "description": "Sum of Male + Female + Unknown sex should equal Live Births",
    },
    {
        "code": "R012",
        "name": "Multiple Pregnancy <= Live Births",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "6.d", "parent": "6"}),
        "description": "Multiple pregnancy count must not exceed Live Births",
    },
    {
        "code": "R013",
        "name": "Twins/Multiples count <= Live Births",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "6.e", "parent": "6"}),
        "description": "Number of twins/multiples must not exceed Live Births",
    },
    {
        "code": "R014",
        "name": "Preterm Births <= Live Births",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "6.f", "parent": "6"}),
        "description": "Preterm births must not exceed Live Births",
    },
    {
        "code": "R015",
        "name": "Low Birth Weight <= Live Births",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "6.g", "parent": "6"}),
        "description": "Low birth weight count must not exceed Live Births",
    },
    {
        "code": "R016",
        "name": "Fresh + Macerated Stillbirth = Fetal Deaths >24w",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "7", "children": ["7.a", "7.b"]}),
        "description": "Sum of fresh and macerated stillbirth should equal Fetal Deaths >24 weeks",
    },
    {
        "code": "R017",
        "name": "First + Second Trimester = Abortions ≤24w",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "eq",
        "params": json.dumps({"parent": "8", "children": ["8.a", "8.b"]}),
        "description": "Sum of first and second trimester abortions should equal total Abortions",
    },
    {
        "code": "R018",
        "name": "Fetal Deaths <= Total Deliveries",
        "rule_type": "LOGIC",
        "severity": "HIGH",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "7", "parent": "2"}),
        "description": "Fetal deaths must not exceed Total Deliveries",
    },
    {
        "code": "R019",
        "name": "Abortions <= Total Deliveries",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "8", "parent": "2"}),
        "description": "Abortions must not exceed Total Deliveries",
    },
    {
        "code": "R020",
        "name": "Congenital Anomalies <= Live Births",
        "rule_type": "LOGIC",
        "severity": "MEDIUM",
        "category": "BASIC_LOGIC",
        "expression_type": "le",
        "params": json.dumps({"child": "9", "parent": "6"}),
        "description": "Congenital anomalies must not exceed Live Births",
    },
    # ============================================
    # GROUP 2: CLINICAL CONSISTENCY (R021-R040)
    # ============================================
    {
        "code": "R021",
        "name": "Postpartum Hemorrhage <= Hemorrhage",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.a.1", "parent": "10.a"}),
        "description": "Postpartum hemorrhage must not exceed total Hemorrhage",
    },
    {
        "code": "R022",
        "name": "Antepartum Hemorrhage <= Hemorrhage",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.a.2", "parent": "10.a"}),
        "description": "Antepartum hemorrhage must not exceed total Hemorrhage",
    },
    {
        "code": "R023",
        "name": "Early Pregnancy Hemorrhage <= Hemorrhage",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.a.3", "parent": "10.a"}),
        "description": "Early pregnancy hemorrhage must not exceed total Hemorrhage",
    },
    {
        "code": "R024",
        "name": "Primary + Secondary Severe PPH <= Postpartum Hemorrhage",
        "rule_type": "CLINICAL",
        "severity": "MEDIUM",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le_sum",
        "params": json.dumps({"child": "10.a.1", "children": ["10.a.1.1", "10.a.1.2"]}),
        "description": "Sum of primary and secondary severe PPH must not exceed Postpartum Hemorrhage",
    },
    {
        "code": "R025",
        "name": "Placental Abruption + Previa <= Antepartum Hemorrhage",
        "rule_type": "CLINICAL",
        "severity": "MEDIUM",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le_sum",
        "params": json.dumps({"child": "10.a.2", "children": ["10.a.2.1", "10.a.2.2"]}),
        "description": "Sum of placental abruption and previa must not exceed Antepartum Hemorrhage",
    },
    {
        "code": "R026",
        "name": "Ectopic + Abortion Bleeding + Molar <= Early Pregnancy Hemorrhage",
        "rule_type": "CLINICAL",
        "severity": "MEDIUM",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le_sum",
        "params": json.dumps({"child": "10.a.3", "children": ["10.a.3.1", "10.a.3.2", "10.a.3.3"]}),
        "description": "Sum of ectopic, abortion bleeding, and molar must not exceed Early Pregnancy Hemorrhage",
    },
    {
        "code": "R027",
        "name": "Severe Preeclampsia <= Hypertensive Disorders",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.e.1", "parent": "10.e"}),
        "description": "Severe preeclampsia must not exceed total Hypertensive Disorders",
    },
    {
        "code": "R028",
        "name": "HELLP Syndrome <= Hypertensive Disorders",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.e.2", "parent": "10.e"}),
        "description": "HELLP syndrome must not exceed total Hypertensive Disorders",
    },
    {
        "code": "R029",
        "name": "Eclampsia <= Hypertensive Disorders",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.e.3", "parent": "10.e"}),
        "description": "Eclampsia must not exceed total Hypertensive Disorders",
    },
    {
        "code": "R030",
        "name": "Preeclampsia + HELLP + Eclampsia <= Hypertensive Disorders",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.e", "parent": "10.e", "children": ["10.e.1", "10.e.2", "10.e.3"]}),
        "description": "Sum of severe preeclampsia, HELLP, and eclampsia must not exceed Hypertensive Disorders",
    },
    {
        "code": "R031",
        "name": "Hemorrhage <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.a", "parent": "10"}),
        "description": "Hemorrhage must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R032",
        "name": "Hypertensive Disorders <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.e", "parent": "10"}),
        "description": "Hypertensive disorders must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R033",
        "name": "Sepsis <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.f", "parent": "10"}),
        "description": "Sepsis must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R034",
        "name": "Unplanned ICU Admission <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.m", "parent": "10"}),
        "description": "Unplanned ICU admission must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R035",
        "name": "Hysterectomy <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.d", "parent": "10"}),
        "description": "Hysterectomy must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R036",
        "name": "Relaparotomy <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.c", "parent": "10"}),
        "description": "Relaparotomy must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R037",
        "name": "Uterine Rupture <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.b", "parent": "10"}),
        "description": "Uterine rupture must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R038",
        "name": "Anaesthesia Complications <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "MEDIUM",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.l", "parent": "10"}),
        "description": "Anaesthesia complications must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R039",
        "name": "Cardiac ICU Admission <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.h", "parent": "10"}),
        "description": "Cardiac ICU admission must not exceed total Severe Maternal Morbidity",
    },
    {
        "code": "R040",
        "name": "Renal Failure/Dialysis <= Severe Maternal Morbidity",
        "rule_type": "CLINICAL",
        "severity": "HIGH",
        "category": "CLINICAL_CONSISTENCY",
        "expression_type": "le",
        "params": json.dumps({"child": "10.i", "parent": "10"}),
        "description": "Renal failure/dialysis must not exceed total Severe Maternal Morbidity",
    },
    # ============================================
    # GROUP 3: STATISTICAL & BENCHMARK (R041-R050)
    # ============================================
    {
        "code": "R041",
        "name": "C-Section Rate > 80% alert",
        "rule_type": "BENCHMARK",
        "severity": "HIGH",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "benchmark_rate",
        "params": json.dumps({"num_code": "5", "den_code": "2", "threshold": 80.0}),
        "description": "C-Section rate exceeding 80% triggers an alert",
    },
    {
        "code": "R042",
        "name": "NVD Rate < 10% alert",
        "rule_type": "BENCHMARK",
        "severity": "HIGH",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "benchmark_low_rate",
        "params": json.dumps({"num_code": "3", "den_code": "2", "threshold": 10.0}),
        "description": "Normal vaginal delivery rate below 10% triggers an alert",
    },
    {
        "code": "R043",
        "name": "Preterm Birth Rate outlier detection",
        "rule_type": "BENCHMARK",
        "severity": "MEDIUM",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "6.f", "den_code": "6", "z_threshold": 2.5}),
        "description": "Preterm birth rate compared across hospitals for outlier detection",
    },
    {
        "code": "R044",
        "name": "Low Birth Weight Rate outlier detection",
        "rule_type": "BENCHMARK",
        "severity": "MEDIUM",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "6.g", "den_code": "6", "z_threshold": 2.5}),
        "description": "Low birth weight rate compared across hospitals for outlier detection",
    },
    {
        "code": "R045",
        "name": "Maternal Mortality Ratio cross-hospital comparison",
        "rule_type": "BENCHMARK",
        "severity": "HIGH",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "11", "den_code": "6", "z_threshold": 2.5}),
        "description": "Maternal mortality ratio compared across hospitals",
    },
    {
        "code": "R046",
        "name": "Neonatal Mortality Rate cross-hospital comparison",
        "rule_type": "BENCHMARK",
        "severity": "HIGH",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "17", "den_code": "6", "z_threshold": 2.5}),
        "description": "Neonatal mortality rate compared across hospitals",
    },
    {
        "code": "R047",
        "name": "Stillbirth Rate cross-hospital comparison",
        "rule_type": "BENCHMARK",
        "severity": "MEDIUM",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "7", "den_code": "2", "z_threshold": 2.5}),
        "description": "Stillbirth rate compared across hospitals",
    },
    {
        "code": "R048",
        "name": "NICU Admission Rate cross-hospital comparison",
        "rule_type": "BENCHMARK",
        "severity": "MEDIUM",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "16", "den_code": "6", "z_threshold": 2.5}),
        "description": "NICU admission rate compared across hospitals",
    },
    {
        "code": "R049",
        "name": "SMM Rate cross-hospital comparison",
        "rule_type": "BENCHMARK",
        "severity": "HIGH",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "10", "den_code": "2", "z_threshold": 2.5}),
        "description": "Severe Maternal Morbidity rate compared across hospitals",
    },
    {
        "code": "R050",
        "name": "Hemorrhage Rate cross-hospital comparison",
        "rule_type": "BENCHMARK",
        "severity": "HIGH",
        "category": "STATISTICAL_BENCHMARK",
        "expression_type": "cross_hospital_rate",
        "params": json.dumps({"num_code": "10.a", "den_code": "2", "z_threshold": 2.5}),
        "description": "Hemorrhage rate compared across hospitals",
    },
    # ============================================
    # GROUP 4: TREND & DATA QUALITY (R051-R060)
    # ============================================
    {
        "code": "R051",
        "name": "Deliveries > 2x previous month",
        "rule_type": "DATA_QUALITY",
        "severity": "HIGH",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "month_over",
        "params": json.dumps({"code": "2", "factor": 2.0}),
        "description": "Current month deliveries exceed 2x previous month - investigate",
    },
    {
        "code": "R052",
        "name": "Deliveries < 50% of previous month",
        "rule_type": "DATA_QUALITY",
        "severity": "HIGH",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "month_under",
        "params": json.dumps({"code": "2", "factor": 0.5}),
        "description": "Current month deliveries dropped below 50% of previous month - investigate",
    },
    {
        "code": "R053",
        "name": "Live Births > 2x previous month",
        "rule_type": "DATA_QUALITY",
        "severity": "HIGH",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "month_over",
        "params": json.dumps({"code": "6", "factor": 2.0}),
        "description": "Current month live births exceed 2x previous month - investigate",
    },
    {
        "code": "R054",
        "name": "Maternal Deaths increased by >300%",
        "rule_type": "DATA_QUALITY",
        "severity": "CRITICAL",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "month_over",
        "params": json.dumps({"code": "11", "factor": 4.0}),
        "description": "Maternal deaths increased by more than 300% compared to previous month",
    },
    {
        "code": "R055",
        "name": "Neonatal Deaths increased by >300%",
        "rule_type": "DATA_QUALITY",
        "severity": "CRITICAL",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "month_over",
        "params": json.dumps({"code": "17", "factor": 4.0}),
        "description": "Neonatal deaths increased by more than 300% compared to previous month",
    },
    {
        "code": "R056",
        "name": "Negative indicator value found",
        "rule_type": "DATA_QUALITY",
        "severity": "HIGH",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "neg_check",
        "params": json.dumps({"codes": ["2", "3", "4", "5", "6", "7", "8", "10", "11", "16", "17"]}),
        "description": "Any indicator value is negative (counts should be >= 0)",
    },
    {
        "code": "R057",
        "name": "Decimal value for count indicator",
        "rule_type": "DATA_QUALITY",
        "severity": "LOW",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "decimal_check",
        "params": json.dumps({"codes": ["2", "3", "4", "5", "6", "7", "8", "10", "11", "16", "17"]}),
        "description": "Any indicator value is a decimal (counts should be integers)",
    },
    {
        "code": "R058",
        "name": "Missing Total Deliveries",
        "rule_type": "DATA_QUALITY",
        "severity": "HIGH",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "missing",
        "params": json.dumps({"code": "2"}),
        "description": "Total Deliveries indicator is missing",
    },
    {
        "code": "R059",
        "name": "Missing Live Births",
        "rule_type": "DATA_QUALITY",
        "severity": "HIGH",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "missing",
        "params": json.dumps({"code": "6"}),
        "description": "Live Births indicator is missing",
    },
    {
        "code": "R060",
        "name": "All indicators zero (possible non-operational facility)",
        "rule_type": "DATA_QUALITY",
        "severity": "CRITICAL",
        "category": "TREND_DATA_QUALITY",
        "expression_type": "all_zero",
        "params": json.dumps({"codes": ["2", "3", "4", "5", "6", "7", "8", "10", "11", "16", "17"]}),
        "description": "All key indicators are zero for a working facility - data may be missing",
    },
]


def seed_rules(session=None):
    """Seed rules into the database. If no session given, creates one."""
    own_session = session is None
    if own_session:
        init_db()
        session = SessionLocal()
    try:
        count = session.query(Rule).count()
        if count > 0:
            if own_session:
                print(f"Rules table already has {count} rules. Skipping seed.")
            return

        for idx, r in enumerate(RULES):
            rule = Rule(
                code=r["code"],
                name=r["name"],
                rule_type=r["rule_type"],
                severity=r["severity"],
                category=r["category"],
                expression_type=r["expression_type"],
                params=r["params"],
                description=r["description"],
                sort_order=idx,
            )
            session.add(rule)
        session.commit()
        if own_session:
            print(f"Seeded {len(RULES)} rules successfully.")
    finally:
        if own_session:
            session.close()


if __name__ == "__main__":
    seed_rules()
